export const ADD_TODO = "ADD_TODO";
export const ADD_LOCATION = "ADD_LOCATION";
export const DELETE_TODO = "DELETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL_TODOS = "COMPLETE_ALL_TODOS";
export const CLEAR_ALL = "CLEAR_ALL";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const ADD_WARNING = "ADD_WARNING";
export const MOVE_TRACK_ENTRY = "MOVEE_TRACK_ENTRY";
export const DELETE_TRACK_ENTRY = "DELETE_TRACK_ENTRY";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const EDIT_WARNING = "EDIT_WARNING";
export const DELETE_WARNING = "DELETE_WARNING";

export const SET_DETAIL = "SET_DETAIL";
export const GENERATE_WARNINGS = "GENERATE_WARNINGS";
export const COMPLETE_WARNING = "COMPLETE_WARNING";
export const COMPLETE_ALL_WARNINGS = "COMPLETE_ALL_WARNINGS";
export const API_CALL_REPORT_REQUEST = "API_CALL_REPORT_REQUEST";
export const API_CALL_REPORT_SUCCESS = "API_CALL_REPORT_SUCCESS";
export const API_CALL_REPORT_FAILURE = "API_CALL_REPORT_FAILURE";

export const API_CALL_INFECTIONS_REQUEST = "API_CALL_INFECTIONS_REQUEST";
export const API_CALL_INFECTIONS_SUCCESS = "API_CALL_INFECTIONS_SUCCESS";
export const API_CALL_INFECTIONS_FAILURE = "API_CALL_INFECTIONS_FAILURE";
export const GENERATE_FAKE_INFECTIONS = "GENERATE_FAKE_INFECTIONS";

export const API_CALL_CASE_REQUEST = "API_CALL_CASE_REQUEST";
export const API_CALL_CASE_SUCCESS = "API_CALL_CASE_SUCCESS";
export const API_CALL_CASE_FAILURE = "API_CALL_CASE_FAILURE";

export const ADD_TRACK = "ADD_TRACK";
